--From http://www.imdb.com/list/ls074818782/

IF NOT EXISTS (SELECT 1 FROM dbo.Movies)
BEGIN
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Ghost in the Shell 2: Innocence', 7.6, 2004, 'In the year 2032, Batô, a cyborg detective for the anti-terrorist unit Public Security Section 9, investigates the case of a female robot--one created solely for sexual pleasure--who slaughtered her owner. (100 mins.)', './assests/img/film/Ghost in the Shell 2 Innocence (2004).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Zootopia', 8.1, 2016, 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy. (108 mins.)', './assests/img/film/Zootopia (2016).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Spirited Away', 8.6, 2001, 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', './assests/img/film/Spirited Away (2001).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Inside Out', 8.2, 2015, 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.', './assests/img/film/Inside Out (2015).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Anomalisa', 7.3, 2015, 'A man crippled by the mundanity of his life experiences something out of the ordinary.', './assests/img/film/Anomalisa (2015).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('WALL-E', 8.4, 2008, 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', './assests/img/film/WALL-E (2008).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Toy Story 3', 8.3, 2010, 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it''s up to Woody to convince the other toys that they weren''t abandoned and to return home.', './assests/img/film/Toy Story 3 (2010).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Up', 8.3, 2009, 'Seventy-eight year old Carl Fredricksen travels to Paradise Falls in his home equipped with balloons, inadvertently taking a young stowaway.', './assests/img/film/Up (2009).jpg')
	INSERT INTO Movies (Name, Imdb, Year, Description, ImageUrl) VALUES ('Howl''s Moving Castle', 8.2, 2004, 'When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.', './assests/img/film/Howl''s Moving Castle (2004).jpg')
END